name = "pali-server"
main = "build/worker/shim.mjs"
compatibility_date = "2025-08-27"

[[d1_databases]]
binding = "DB"
database_name = "pali-database"
database_id = "YOUR_DATABASE_ID"

[vars]
# Initial admin API key for first-time setup
# Generate a secure key and set this value
INITIAL_ADMIN_KEY = "change-this-to-a-secure-key"

[build]
command = "cargo install -q worker-build && worker-build --release"